default_platform(:ios)

platform :ios do
  desc "Build .ipa for distribution"
  lane :release do
  clear_derived_data 
    build_app(
      scheme: "trainingtask",
      workspace: "trainingtask.xcworkspace",
      output_directory: "./build",
      output_name: "trainingtask.ipa",
      export_method: "app-store", 
    )
  end
  
  desc "To export app"
  lane :export_app do
    gym(
      project: "trainingtask.xcodeproj",
      scheme: "trainingtask",
      configuration: "Debug",
      output_directory: "./build",
      output_name: "trainingtask_dev.ipa",
      export_method: "app-store",
      clean: true,
      skip_codesigning: false
    )
  end
end