# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the iOS application"
  lane :build do
    build_ios_app(
      scheme: "trainingtask",
      workspace: "trainingtask.xcworkspace",
      output_directory: "./build",
      output_name: "trainingtask.app",
      destination: "platform=iOS Simulator,name=iPhone 15",
      silent: false,
      clean: true,
      skip_codesigning: true,
      export_method: "development",
      skip_archive: true,
      configuration: "Debug"
    )
  end
end
